apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-mult
  namespace: hm7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo "current date = $(date)" >> /shared/date.log; sleep 5; done']
        volumeMounts:
          - name: shared-volume
            mountPath: /shared

      - name: multitool
        image: wbitt/network-multitool
        command: ['sh', '-c', 'while true; do cat /shared/date.log; sleep 5; done']
        volumeMounts:
          - name: shared-volume
            mountPath: /shared

      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: pvc-vol
